### ISSUE TITLE
Bug when /usr/bin/python is Python 3

### ISSUE THREAD

**Issue by Asher256** [apprenda/kismatic#282]
This bug happened because /usr/bin/python points to python 3 in some operating systems (like Arch Linux):
```
2017-02-09 01:01:32.398+0000 - export PYTHONPATH=/home/workshop/hands-on-with-kubernetes-workshop/ansible/lib/python2.7/site-packages:/home/workshop/hands-on-with-kubernetes-workshop/ansible/lib64/python2.7/site-packages
2017-02-09 01:01:32.398+0000 - export ANSIBLE_CALLBACK_PLUGINS=ansible/playbooks/callback
2017-02-09 01:01:32.398+0000 - export ANSIBLE_CALLBACK_WHITELIST=json_lines
2017-02-09 01:01:32.398+0000 - export ANSIBLE_CONFIG=ansible/playbooks/ansible.cfg
2017-02-09 01:01:32.398+0000 - export ANSIBLE_JSON_LINES_PIPE=/tmp/ansible-pipe-2296349169875352194-2017-02-08-20-01-32.39856
2017-02-09 01:01:32.398+0000 - ansible/bin/ansible-playbook -i ansible/inventory.ini -s ansible/playbooks/preflight.yaml --extra-vars @ansible/clustercatalog.yaml -vvvv
2017-02-09 01:01:32.429+0000 - Traceback (most recent call last):
2017-02-09 01:01:32.429+0000 -   File "ansible/bin/ansible-playbook", line 36, in <module>
2017-02-09 01:01:32.429+0000 -     import shutil
2017-02-09 01:01:32.429+0000 -   File "/usr/lib/python3.6/shutil.py", line 10, in <module>
2017-02-09 01:01:32.429+0000 -     import fnmatch
2017-02-09 01:01:32.429+0000 -   File "/usr/lib/python3.6/fnmatch.py", line 14, in <module>
2017-02-09 01:01:32.429+0000 -     import re
2017-02-09 01:01:32.429+0000 -   File "/usr/lib/python3.6/re.py", line 142, in <module>
2017-02-09 01:01:32.429+0000 -     class RegexFlag(enum.IntFlag):
2017-02-09 01:01:32.429+0000 - AttributeError: module 'enum' has no attribute 'IntFlag'
```

**Comment by Asher256** [comment]
Moved to:
https://github.com/swade1987/hands-on-with-kubernetes-workshop/issues/new

**Comment by davidhiendl** [comment]
This is still broken on Arch Linux where Python is on version 3.6.*
The workshop also does not modify the environment in any way and just calls `kismatic ...` directly from the Makefile which leads to the same problem.

**Comment by emmetthitz** [comment]
This is related to the fact that ansible expects Python 2. It's not something we can trivially fix without upstream support.

**Comment by davidhiendl** [comment]
I've actually found a rather simple workaround while trying to use kismatic from my Arch workspace: Modify the Shebang of each ansible script to point to python2:
```bash
#!/usr/bin/python2
```
Alternatively the kismatic CLI could invoke the correct python version directly (eg. check if /usr/bin/python2 symlink exists, which it should nearly everywhere) and then use it.
An other alternative would be to offer a flag to manually specify the python path.

I also think that the CLI should verify that the correct python dependency exists (e.g. check python version).
