### ISSUE TITLE
Upgrades: kube-apiserver failed to start after upgrade

### ISSUE THREAD

**Issue by dkoshkin** [apprenda/kismatic#374]
**KET Version**: v1.1.1
**OS**: Ubuntu

etcd node was updated and when upgrading master `kube-apiserver` didn't start correctly
 
```
I0303 20:15:50.903345       1 config.go:527] Will report 192.168.42.3 as public IP address.
I0303 20:15:50.903448       1 server.go:148] Initalizing deserialization cache size based on 0MB limit
I0303 20:15:50.904826       1 server.go:342] Initalizing cache sizes based on 0MB limit
E0303 20:15:50.937712       1 reflector.go:199] k8s.io/kubernetes/plugin/pkg/admission/resourcequota/resource_access.go:83: Failed to list *api.ResourceQuota: Get http://127.0.0.1:8080/api/v1/resourcequotas?resourceVersion=0: dial tcp 127.0.0.1:8080: getsockopt: connection refused
E0303 20:15:50.937885       1 reflector.go:199] k8s.io/kubernetes/plugin/pkg/admission/storageclass/default/admission.go:75: Failed to list *storage.StorageClass: Get http://127.0.0.1:8080/apis/storage.k8s.io/v1beta1/storageclasses?resourceVersion=0: dial tcp 127.0.0.1:8080: getsockopt: connection refused
E0303 20:15:50.937965       1 reflector.go:199] k8s.io/kubernetes/plugin/pkg/admission/serviceaccount/admission.go:119: Failed to list *api.Secret: Get http://127.0.0.1:8080/api/v1/secrets?fieldSelector=type%3Dkubernetes.io%2Fservice-account-token&resourceVersion=0: dial tcp 127.0.0.1:8080: getsockopt: connection refused
E0303 20:15:50.938043       1 reflector.go:199] k8s.io/kubernetes/plugin/pkg/admission/serviceaccount/admission.go:103: Failed to list *api.ServiceAccount: Get http://127.0.0.1:8080/api/v1/serviceaccounts?resourceVersion=0: dial tcp 127.0.0.1:8080: getsockopt: connection refused
I0303 20:15:50.950036       1 master.go:310] Enabling API group "apps".
I0303 20:15:50.950149       1 master.go:310] Enabling API group "authentication.k8s.io".
I0303 20:15:50.950182       1 master.go:310] Enabling API group "authorization.k8s.io".
I0303 20:15:50.950879       1 master.go:310] Enabling API group "autoscaling".
I0303 20:15:50.951617       1 master.go:310] Enabling API group "batch".
I0303 20:15:50.952280       1 master.go:310] Enabling API group "certificates.k8s.io".
I0303 20:15:50.959046       1 master.go:310] Enabling API group "extensions".
I0303 20:15:50.959738       1 master.go:310] Enabling API group "policy".
I0303 20:15:50.965457       1 master.go:310] Enabling API group "rbac.authorization.k8s.io".
I0303 20:15:50.966730       1 master.go:310] Enabling API group "storage.k8s.io".
[restful] 2017/03/03 20:15:51 log.go:30: [restful/swagger] listing is available at https://192.168.42.3:6443/swaggerapi/
[restful] 2017/03/03 20:15:51 log.go:30: [restful/swagger] https://192.168.42.3:6443/swaggerui/ is mapped to folder /swagger-ui/
E0303 20:15:51.052472       1 reflector.go:199] pkg/controller/informers/factory.go:89: Failed to list *api.Namespace: Get http://127.0.0.1:8080/api/v1/namespaces?resourceVersion=0: dial tcp 127.0.0.1:8080: getsockopt: connection refused
E0303 20:15:51.052669       1 reflector.go:199] pkg/controller/informers/factory.go:89: Failed to list *api.LimitRange: Get http://127.0.0.1:8080/api/v1/limitranges?resourceVersion=0: dial tcp 127.0.0.1:8080: getsockopt: connection refused
I0303 20:15:51.063443       1 serve.go:88] Serving securely on 0.0.0.0:6443
I0303 20:15:51.063610       1 serve.go:102] Serving insecurely on 127.0.0.1:8080
I0303 20:16:01.902208       1 trace.go:61] Trace "Create /api/v1/namespaces/kube-system/pods" (started 2017-03-03 20:15:51.901181229 +0000 UTC):
[429.352µs] [429.352µs] About to convert to expected version
[569.076µs] [139.724µs] Conversion done
[10.000992935s] [10.000423859s] END
I0303 20:16:01.902292       1 panics.go:76] POST /api/v1/namespaces/kube-system/pods: (10.001096582s) 403 [[kubelet/v1.5.3 (linux/amd64) kubernetes/029c3a4] 192.168.42.3:48178]
I0303 20:16:06.283240       1 trace.go:61] Trace "Create /api/v1/namespaces/kube-system/events" (started 2017-03-03 20:15:56.281639557 +0000 UTC):
[297.475µs] [297.475µs] About to convert to expected version
[407.179µs] [109.704µs] Conversion done
[10.001569045s] [10.001161866s] END
I0303 20:16:06.283264       1 panics.go:76] POST /api/v1/namespaces/kube-system/events: (10.001851487s) 403 [[kubelet/v1.5.3 (linux/amd64) kubernetes/029c3a4] 192.168.42.3:48178]
I0303 20:16:06.900927       1 trace.go:61] Trace "Create /api/v1/namespaces/kube-system/events" (started 2017-03-03 20:15:56.899793702 +0000 UTC):
[640.129µs] [640.129µs] About to convert to expected version
[762.727µs] [122.598µs] Conversion done
[10.001105492s] [10.000342765s] END
I0303 20:16:06.900974       1 panics.go:76] POST /api/v1/namespaces/kube-system/events: (10.001330964s) 403 [[kubelet/v1.5.1 (linux/amd64) kubernetes/82450d0] 192.168.42.4:45340]
I0303 20:16:14.064990       1 panics.go:76] GET /healthz: (118.886µs) 500
goroutine 553 [running]:
k8s.io/kubernetes/pkg/httplog.(*respLogger).recordStatus(0xc42155fb90, 0x1f4)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/httplog/log.go:219 +0xbb
k8s.io/kubernetes/pkg/httplog.(*respLogger).WriteHeader(0xc42155fb90, 0x1f4)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/httplog/log.go:198 +0x35
net/http.Error(0x4ab11c0, 0xc42155fb90, 0xc421cdab40, 0xbf, 0x1f4)
	/usr/local/go/src/net/http/server.go:1738 +0xda
k8s.io/kubernetes/pkg/healthz.handleRootHealthz.func1(0x4ab11c0, 0xc42155fb90, 0xc421706000)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/healthz/healthz.go:109 +0x490
net/http.HandlerFunc.ServeHTTP(0xc421e845a0, 0x4ab11c0, 0xc42155fb90, 0xc421706000)
	/usr/local/go/src/net/http/server.go:1726 +0x44
net/http.(*ServeMux).ServeHTTP(0xc4201caf30, 0x4ab11c0, 0xc42155fb90, 0xc421706000)
	/usr/local/go/src/net/http/server.go:2022 +0x7f
k8s.io/kubernetes/pkg/genericapiserver/filters.WithPanicRecovery.func1(0x4ab11c0, 0xc42155fb90, 0xc421706000)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/genericapiserver/filters/panics.go:75 +0x24a
net/http.HandlerFunc.ServeHTTP(0xc42019e240, 0x7fabd532ded8, 0xc420441418, 0xc421706000)
	/usr/local/go/src/net/http/server.go:1726 +0x44
k8s.io/kubernetes/pkg/apiserver/filters.WithRequestInfo.func1(0x7fabd532ded8, 0xc420441418, 0xc421706000)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/filters/requestinfo.go:45 +0x212
net/http.HandlerFunc.ServeHTTP(0xc42019e360, 0x7fabd532ded8, 0xc420441418, 0xc421706000)
	/usr/local/go/src/net/http/server.go:1726 +0x44
k8s.io/kubernetes/pkg/api.WithRequestContext.func1(0x7fabd532ded8, 0xc420441418, 0xc421706000)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/api/requestcontext.go:107 +0xef
net/http.HandlerFunc.ServeHTTP(0xc420728b60, 0x7fabd532ded8, 0xc420441418, 0xc421706000)
	/usr/local/go/src/net/http/server.go:1726 +0x44
k8s.io/kubernetes/pkg/genericapiserver/filters.(*timeoutHandler).ServeHTTP.func1(0xc420728b80, 0x4ab6700, 0xc420441418, 0xc421706000, 0xc4217c50e0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/genericapiserver/filters/timeout.go:78 +0x8d
created by k8s.io/kubernetes/pkg/genericapiserver/filters.(*timeoutHandler).ServeHTTP
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/genericapiserver/filters/timeout.go:80 +0x1db

logging error output: "[-]poststarthook/bootstrap-controller failed: not finished\n[+]poststarthook/extensions/third-party-resources ok\n[-]poststarthook/rbac/bootstrap-roles failed: not finished\nhealthz check failed\n"
 [[Go-http-client/1.1] 127.0.0.1:54330]
I0303 20:16:15.897999       1 trace.go:61] Trace "Get /api/v1/namespaces/kube-system/pods/kube-apiserver-master001" (started 2017-03-03 20:15:56.714786338 +0000 UTC):
[19.183166155s] [19.183166155s] END
E0303 20:16:15.898029       1 errors.go:63] apiserver received an error that is not an unversioned.Status: client: etcd cluster is unavailable or misconfigured
I0303 20:16:15.898318       1 panics.go:76] GET /api/v1/namespaces/kube-system/pods/kube-apiserver-master001: (19.183992121s) 500
goroutine 514 [running]:
k8s.io/kubernetes/pkg/httplog.(*respLogger).recordStatus(0xc42155e850, 0x1f4)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/httplog/log.go:219 +0xbb
k8s.io/kubernetes/pkg/httplog.(*respLogger).WriteHeader(0xc42155e850, 0x1f4)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/httplog/log.go:198 +0x35
k8s.io/kubernetes/pkg/apiserver/metrics.(*responseWriterDelegator).WriteHeader(0xc421cca540, 0x1f4)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/metrics/metrics.go:117 +0x45
k8s.io/kubernetes/pkg/apiserver.writeNegotiated(0x4ab4980, 0xc42036ec60, 0x0, 0x0, 0x29af9f5, 0x2, 0x4ab0cc0, 0xc420440fd8, 0xc421b42ff0, 0x1f4, ...)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go:463 +0x162
k8s.io/kubernetes/pkg/apiserver.errorNegotiated(0x4a9b280, 0xc421d8d500, 0x4ab4980, 0xc42036ec60, 0x0, 0x0, 0x29af9f5, 0x2, 0x4ab0cc0, 0xc420440fd8, ...)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go:480 +0x103
k8s.io/kubernetes/pkg/apiserver.(*RequestScope).err(0xc420a93960, 0x4a9b280, 0xc421d8d500, 0x4ab0cc0, 0xc420440fd8, 0xc421b42ff0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/resthandler.go:88 +0xd7
k8s.io/kubernetes/pkg/apiserver.getResourceHandler.func1(0xc421cca480, 0xc421ad5920)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/resthandler.go:113 +0x20d
k8s.io/kubernetes/pkg/apiserver/metrics.InstrumentRouteFunc.func1(0xc421cca480, 0xc421ad5920)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/metrics/metrics.go:101 +0x1f2
k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).dispatch(0xc4206f6f30, 0x4ab11c0, 0xc42155e850, 0xc421b42ff0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:272 +0xba0
k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).(k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.dispatch)-fm(0x4ab11c0, 0xc42155e850, 0xc421b42ff0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:120 +0x48
net/http.HandlerFunc.ServeHTTP(0xc4202bca70, 0x4ab11c0, 0xc42155e850, 0xc421b42ff0)
	/usr/local/go/src/net/http/server.go:1726 +0x44
net/http.(*ServeMux).ServeHTTP(0xc4201caf30, 0x4ab11c0, 0xc42155e850, 0xc421b42ff0)
	/usr/local/go/src/net/http/server.go:2022 +0x7f
k8s.io/kubernetes/pkg/apiserver/filters.WithAuthorization.func1(0x4ab11c0, 0xc42155e850, 0xc421b42ff0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/filters/authorization.go:44 +0x2fc
net/http.HandlerFunc.ServeHTTP(0xc420371900, 0x4ab11c0, 0xc42155e850, 0xc421b42ff0)
	/usr/local/go/src/net/http/server.go:1726 +0x44
k8s.io/kubernetes/pkg/apiserver/filters.WithImpersonation.func1(0x4ab11c0, 0xc42155e850, 0xc421b42ff0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/filters/impersonation.go:44 +0x1b07
net/http.HandlerFunc.ServeHTTP(0xc420371940, 0x4ab11c0, 0xc42155e850, 0xc421b42ff0)
	/usr/local/go/src/net/http/server.go:1726 +0x44
k8s.io/kubernetes/pkg/auth/handlers.WithAuthentication.func1(0x4ab11c0, 0xc42155e850, 0xc421b42ff0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/auth/handlers/handlers.go:73 +0x2c2
net/http.HandlerFunc.ServeHTTP(0xc420712910, 0x4ab11c0, 0xc42155e850, 0xc421b42ff0)
	/usr/local/go/src/net/http/server.go:1726 +0x44
k8s.io/kubernetes/pkg/api.WithRequestContext.func1(0x4ab11c0, 0xc42155e850, 0xc421b42ff0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/api/requestcontext.go:107 +0xef
net/http.HandlerFunc.ServeHTTP(0xc420728980, 0x4ab11c0, 0xc42155e850, 0xc421b42ff0)
	/usr/local/go/src/net/http/server.go:1726 +0x44
k8s.io/kubernetes/pkg/genericapiserver/filters.WithPanicRecovery.func1(0x4ab11c0, 0xc42155e850, 0xc421b42ff0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/genericapiserver/filters/panics.go:75 +0x24a
net/http.HandlerFunc.ServeHTTP(0xc42019e090, 0x7fabd5339750, 0xc420440f88, 0xc421b42ff0)
	/usr/local/go/src/net/http/server.go:1726 +0x44
k8s.io/kubernetes/pkg/apiserver/filters.WithRequestInfo.func1(0x7fabd5339750, 0xc420440f88, 0xc421b42ff0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/filters/requestinfo.go:45 +0x212
net/http.HandlerFunc.ServeHTTP(0xc42019e180, 0x7fabd5339750, 0xc420440f88, 0xc421b42ff0)
	/usr/local/go/src/net/http/server.go:1726 +0x44
k8s.io/kubernetes/pkg/api.WithRequestContext.func1(0x7fabd5339750, 0xc420440f88, 0xc421b42ff0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/api/requestcontext.go:107 +0xef
net/http.HandlerFunc.ServeHTTP(0xc420728a60, 0x7fabd5339750, 0xc420440f88, 0xc421b42ff0)
	/usr/local/go/src/net/http/server.go:1726 +0x44
k8s.io/kubernetes/pkg/genericapiserver/filters.(*timeoutHandler).ServeHTTP.func1(0xc420728a80, 0x4ab6740, 0xc420440f88, 0xc421b42ff0, 0xc421ad57a0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/genericapiserver/filters/timeout.go:78 +0x8d
created by k8s.io/kubernetes/pkg/genericapiserver/filters.(*timeoutHandler).ServeHTTP
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/genericapiserver/filters/timeout.go:80 +0x1db

logging error output: "{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"client: etcd cluster is unavailable or misconfigured\",\"code\":500}\n"
 [[kubectl/v1.5.3 (linux/amd64) kubernetes/029c3a4] 192.168.42.3:48222]
I0303 20:16:16.285850       1 trace.go:61] Trace "Create /api/v1/namespaces/kube-system/events" (started 2017-03-03 20:16:06.285322833 +0000 UTC):
[115.26µs] [115.26µs] About to convert to expected version
[189.479µs] [74.219µs] Conversion done
[10.000497254s] [10.000307775s] END
```

**Comment by dkoshkin** [comment]
Starting a test `kube-apiserver` as a systemd service works fine.

**Comment by dkoshkin** [comment]
Worked fine if a cluster has only 1 etcd node.

**Comment by dkoshkin** [comment]
Cannot reproduce in NYC office using Vagrant or AWS

**Comment by alexbrand** [comment]
@dkoshkin Should we close this?
