### ISSUE TITLE
apiserver not starting on new v1.3 installation

### ISSUE THREAD

**Issue by TimWoolford** [apprenda/kismatic#485]
Installing on clean VMs using kismatic 1.3.0 and 1.3.1-beta0

Install fails to validate apiserver version giving error:
```
Validate Kubernetes Control Plane is Running                                    [ERROR]
- Task: wait until kube-apiserver-vm002805 pod has the desired version
  vm002805:                                                                     [ERROR]
---- STDERR ----
The connection to the server 127.0.0.1:6443 was refused - did you specify the right host or port?
---------------
  vm002806:                                                                     [ERROR]
---- STDERR ----
The connection to the server 127.0.0.1:6443 was refused - did you specify the right host or port?
---------------
error installing: error running playbook: error running ansible: exit status 2
```

This error also occurs using ```kubectl get pods``` on either master, intermittently kubectl returns 'No Resources'. It looks like the apiserver pod is being constantly restarted as the healthz check is not passing.

[apiserver container logs](https://github.com/apprenda/kismatic/files/908379/apiserver-logs.txt)

I suspect the relevant error is:
```
logging error output: "
[+]ping ok\n
[-]poststarthook/bootstrap-controller failed: reason withheld\n
[+]poststarthook/extensions/third-party-resources ok\n
[-]poststarthook/rbac/bootstrap-roles failed: reason withheld\n
[-]poststarthook/ca-registration failed: reason withheld\n
healthz check failed\n"
```

**Comment by alexbrand** [comment]
Hey @TimWoolford 

Looks like the output of the healthz checks was changed recently upstream. Previously, the actual error would have showed up in the logs, but it looks like they are being redacted because this endpoint is public by default.

I _believe_ we can get the actual error messages at the following endpoints on the API Server:
```
"/healthz/poststarthook/bootstrap-controller"
"/healthz/poststarthook/ca-registration"
"/healthz/poststarthook/rbac/bootstrap-roles"
```

**Comment by TimWoolford** [comment]
Thanks @alexbrand,

All I can get from any of those endpoints is ```internal server error: not finished```

Have to be lucky with timings as the pod gets restarted every few minutes.

**Comment by TimWoolford** [comment]
```
{"log":"I0409 18:44:37.075361       1 wrap.go:75] GET /healthz/poststarthook/ca-registration: (190.889µs) 500\n","stream":"stderr","time":"2017-04-09T18:44:37.075689801Z"}
{"log":"goroutine 2705 [running]:\n","stream":"stderr","time":"2017-04-09T18:44:37.07572998Z"}
{"log":"k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).recordStatus(0xc423a567e0, 0x1f4)\n","stream":"stderr","time":"2017-04-09T18:44:37.075735705Z"}
{"log":"\u0009/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/log.go:219 +0xbb\n","stream":"stderr","time":"2017-04-09T18:44:37.07574769Z"}
{"log":"k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).WriteHeader(0xc423a567e0, 0x1f4)\n","stream":"stderr","time":"2017-04-09T18:44:37.075755956Z"}
{"log":"\u0009/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/log.go:198 +0x35\n","stream":"stderr","time":"2017-04-09T18:44:37.075761429Z"}
{"log":"net/http.Error(0x54fa940, 0xc423a567e0, 0xc423a59ad0, 0x23, 0x1f4)\n","stream":"stderr","time":"2017-04-09T18:44:37.075766599Z"}
{"log":"\u0009/usr/local/go/src/net/http/server.go:1738 +0xda\n","stream":"stderr","time":"2017-04-09T18:44:37.075772032Z"}
{"log":"k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/healthz.adaptCheckToHandler.func1(0x54fa940, 0xc423a567e0, 0xc423a750e0)\n","stream":"stderr","time":"2017-04-09T18:44:37.075777407Z"}
{"log":"\u0009/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/healthz/healthz.go:129 +0xed\n","stream":"stderr","time":"2017-04-09T18:44:37.075782489Z"}
{"log":"net/http.HandlerFunc.ServeHTTP(0xc4221a9440, 0x54fa940, 0xc423a567e0, 0xc423a750e0)\n","stream":"stderr","time":"2017-04-09T18:44:37.075800439Z"}
{"log":"\u0009/usr/local/go/src/net/http/server.go:1726 +0x44\n","stream":"stderr","time":"2017-04-09T18:44:37.07580576Z"}
{"log":"net/http.(*ServeMux).ServeHTTP(0xc4207a0360, 0x54fa940, 0xc423a567e0, 0xc423a750e0)\n","stream":"stderr","time":"2017-04-09T18:44:37.075810603Z"}
{"log":"\u0009/usr/local/go/src/net/http/server.go:2022 +0x7f\n","stream":"stderr","time":"2017-04-09T18:44:37.075820902Z"}
{"log":"k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthorization.func1(0x54fa940, 0xc423a567e0, 0xc423a750e0)\n","stream":"stderr","time":"2017-04-09T18:44:37.075825822Z"}
{"log":"\u0009/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/authorization.go:50 +0x365\n","stream":"stderr","time":"2017-04-09T18:44:37.07583097Z"}
{"log":"net/http.HandlerFunc.ServeHTTP(0xc42067a4c0, 0x54fa940, 0xc423a567e0, 0xc423a750e0)\n","stream":"stderr","time":"2017-04-09T18:44:37.075837062Z"}
{"log":"\u0009/usr/local/go/src/net/http/server.go:1726 +0x44\n","stream":"stderr","time":"2017-04-09T18:44:37.075841796Z"}
{"log":"k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithImpersonation.func1(0x54fa940, 0xc423a567e0, 0xc423a750e0)\n","stream":"stderr","time":"2017-04-09T18:44:37.075846678Z"}
{"log":"\u0009/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/impersonation.go:47 +0x1e4d\n","stream":"stderr","time":"2017-04-09T18:44:37.075852089Z"}
{"log":"net/http.HandlerFunc.ServeHTTP(0xc42067a680, 0x54fa940, 0xc423a567e0, 0xc423a750e0)\n","stream":"stderr","time":"2017-04-09T18:44:37.07585728Z"}
{"log":"\u0009/usr/local/go/src/net/http/server.go:1726 +0x44\n","stream":"stderr","time":"2017-04-09T18:44:37.075862025Z"}
{"log":"k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthentication.func1(0x54fa940, 0xc423a567e0, 0xc423a750e0)\n","stream":"stderr","time":"2017-04-09T18:44:37.075866701Z"}
{"log":"\u0009/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/authentication.go:73 +0x2c2\n","stream":"stderr","time":"2017-04-09T18:44:37.075871742Z"}
{"log":"net/http.HandlerFunc.ServeHTTP(0xc4209a7db0, 0x54fa940, 0xc423a567e0, 0xc423a750e0)\n","stream":"stderr","time":"2017-04-09T18:44:37.075876846Z"}
{"log":"\u0009/usr/local/go/src/net/http/server.go:1726 +0x44\n","stream":"stderr","time":"2017-04-09T18:44:37.075881543Z"}
{"log":"k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/request.WithRequestContext.func1(0x54fa940, 0xc423a567e0, 0xc423a750e0)\n","stream":"stderr","time":"2017-04-09T18:44:37.075886558Z"}
{"log":"\u0009/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/request/requestcontext.go:107 +0xef\n","stream":"stderr","time":"2017-04-09T18:44:37.075891497Z"}
{"log":"net/http.HandlerFunc.ServeHTTP(0xc4209af960, 0x54fa940, 0xc423a567e0, 0xc423a750e0)\n","stream":"stderr","time":"2017-04-09T18:44:37.075914865Z"}
{"log":"\u0009/usr/local/go/src/net/http/server.go:1726 +0x44\n","stream":"stderr","time":"2017-04-09T18:44:37.075919616Z"}
{"log":"k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithPanicRecovery.func1(0x54fa940, 0xc423a567e0, 0xc423a750e0)\n","stream":"stderr","time":"2017-04-09T18:44:37.075924745Z"}
{"log":"\u0009/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/wrap.go:74 +0x24a\n","stream":"stderr","time":"2017-04-09T18:44:37.075929685Z"}
{"log":"net/http.HandlerFunc.ServeHTTP(0xc4207a1260, 0x7f31c0b24a00, 0xc420091c38, 0xc423a750e0)\n","stream":"stderr","time":"2017-04-09T18:44:37.075934629Z"}
{"log":"\u0009/usr/local/go/src/net/http/server.go:1726 +0x44\n","stream":"stderr","time":"2017-04-09T18:44:37.075939416Z"}
{"log":"k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1(0xc4209afa00, 0x5503100, 0xc420091c38, 0xc423a750e0, 0xc423b009c0)\n","stream":"stderr","time":"2017-04-09T18:44:37.075949165Z"}
{"log":"\u0009/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:91 +0x8d\n","stream":"stderr","time":"2017-04-09T18:44:37.075954597Z"}
{"log":"created by k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP\n","stream":"stderr","time":"2017-04-09T18:44:37.07595978Z"}
{"log":"\u0009/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:93 +0x1d1\n","stream":"stderr","time":"2017-04-09T18:44:37.075964714Z"}
{"log":"\n","stream":"stderr","time":"2017-04-09T18:44:37.07597021Z"}
{"log":"logging error output: \"internal server error: not finished\\n\"\n","stream":"stderr","time":"2017-04-09T18:44:37.07597461Z"}
```

**Comment by TimWoolford** [comment]
For the rbac endpoint:
```
I0409 19:02:38.707165       1 wrap.go:75] GET /healthz/poststarthook/rbac/bootstrap-roles: (127.509µs) 500
goroutine 2326 [running]:
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).recordStatus(0xc423f6e8c0, 0x1f4)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/log.go:219 +0xbb
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).WriteHeader(0xc423f6e8c0, 0x1f4)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/log.go:198 +0x35
net/http.Error(0x54fa940, 0xc423f6e8c0, 0xc423fc28d0, 0x23, 0x1f4)
	/usr/local/go/src/net/http/server.go:1738 +0xda
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/healthz.adaptCheckToHandler.func1(0x54fa940, 0xc423f6e8c0, 0xc423f68b40)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/healthz/healthz.go:129 +0xed
net/http.HandlerFunc.ServeHTTP(0xc4225d4b30, 0x54fa940, 0xc423f6e8c0, 0xc423f68b40)
	/usr/local/go/src/net/http/server.go:1726 +0x44
net/http.(*ServeMux).ServeHTTP(0xc4201d3da0, 0x54fa940, 0xc423f6e8c0, 0xc423f68b40)
	/usr/local/go/src/net/http/server.go:2022 +0x7f
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthorization.func1(0x54fa940, 0xc423f6e8c0, 0xc423f68b40)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/authorization.go:50 +0x365
net/http.HandlerFunc.ServeHTTP(0xc42020bc40, 0x54fa940, 0xc423f6e8c0, 0xc423f68b40)
	/usr/local/go/src/net/http/server.go:1726 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithImpersonation.func1(0x54fa940, 0xc423f6e8c0, 0xc423f68b40)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/impersonation.go:47 +0x1e4d
net/http.HandlerFunc.ServeHTTP(0xc42020be40, 0x54fa940, 0xc423f6e8c0, 0xc423f68b40)
	/usr/local/go/src/net/http/server.go:1726 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthentication.func1(0x54fa940, 0xc423f6e8c0, 0xc423f68b40)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/authentication.go:73 +0x2c2
net/http.HandlerFunc.ServeHTTP(0xc420629770, 0x54fa940, 0xc423f6e8c0, 0xc423f68b40)
	/usr/local/go/src/net/http/server.go:1726 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/request.WithRequestContext.func1(0x54fa940, 0xc423f6e8c0, 0xc423f68b40)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/request/requestcontext.go:107 +0xef
net/http.HandlerFunc.ServeHTTP(0xc420631b40, 0x54fa940, 0xc423f6e8c0, 0xc423f68b40)
	/usr/local/go/src/net/http/server.go:1726 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.WithPanicRecovery.func1(0x54fa940, 0xc423f6e8c0, 0xc423f68b40)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/wrap.go:74 +0x24a
net/http.HandlerFunc.ServeHTTP(0xc4201cb860, 0x7fb796be3f10, 0xc4225524b8, 0xc423f68b40)
	/usr/local/go/src/net/http/server.go:1726 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1(0xc420631be0, 0x5503100, 0xc4225524b8, 0xc423f68b40, 0xc423fec300)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:91 +0x8d
created by k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:93 +0x1d1

logging error output: "internal server error: not finished\n"
```

**Comment by TimWoolford** [comment]
bootstrap-controller gives a 404 with

```
{
  "paths": [
    "/api",
    "/api/v1",
    "/apis",
    "/apis/apps",
    "/apis/apps/v1beta1",
    "/apis/authentication.k8s.io",
    "/apis/authentication.k8s.io/v1",
    "/apis/authentication.k8s.io/v1beta1",
    "/apis/authorization.k8s.io",
    "/apis/authorization.k8s.io/v1",
    "/apis/authorization.k8s.io/v1beta1",
    "/apis/autoscaling",
    "/apis/autoscaling/v1",
    "/apis/autoscaling/v2alpha1",
    "/apis/batch",
    "/apis/batch/v1",
    "/apis/batch/v2alpha1",
    "/apis/certificates.k8s.io",
    "/apis/certificates.k8s.io/v1beta1",
    "/apis/extensions",
    "/apis/extensions/v1beta1",
    "/apis/policy",
    "/apis/policy/v1beta1",
    "/apis/rbac.authorization.k8s.io",
    "/apis/rbac.authorization.k8s.io/v1alpha1",
    "/apis/rbac.authorization.k8s.io/v1beta1",
    "/apis/settings.k8s.io",
    "/apis/settings.k8s.io/v1alpha1",
    "/apis/storage.k8s.io",
    "/apis/storage.k8s.io/v1",
    "/apis/storage.k8s.io/v1beta1",
    "/healthz",
    "/healthz/ping",
    "/healthz/poststarthook/bootstrap-controller",
    "/healthz/poststarthook/ca-registration",
    "/healthz/poststarthook/extensions/third-party-resources",
    "/healthz/poststarthook/rbac/bootstrap-roles",
    "/logs",
    "/metrics",
    "/swagger-ui/",
    "/swaggerapi/",
    "/ui/",
    "/version"
  ]
}
```

**Comment by alexbrand** [comment]
Thanks @TimWoolford. I was hoping for something more useful than that. I will have to dive into the API server code and look into this more.

One thing we can do that might help diagnose is increase the `initialDelaySeconds` on the `livenessProbe` of the API server. This _might_ get us something more useful in the logs. To do this, open up `/etc/kubernetes/manifests/kube-apiserver.yaml` and set the `initialDelaySeconds` value to 60 seconds, or maybe higher. After making the change, restart the kubelet: `systemctl restart kubelet`.

**Comment by alexbrand** [comment]
API server error log from @TimWoolford:
```
Unable to perform initial IP allocation check: unable to refresh the service IP block: Get 
https://localhost:6443/api/v1/services: dial tcp 10.189.173.96:6443: i/o timeout
```
It seemed weird to me that the API server was trying to open a connection to `localhost`, given that we don't specify that anywhere. After digging more into it, I found the following function in the API server which is what determines what address to use:
```
// LoopbackHostPort returns the host and port loopback REST clients should use
// to contact the server.
func LoopbackHostPort(bindAddress string) (string, string, error) {
    host, port, err := net.SplitHostPort(bindAddress)
    if err != nil {
        // should never happen
        return "", "", fmt.Errorf("invalid server bind address: %q", bindAddress)
    }

    // Value is expected to be an IP or DNS name, not "0.0.0.0".
    if host == "0.0.0.0" {
        // compare MaybeDefaultWithSelfSignedCerts which adds "localhost" to the cert as alternateDNS
        host = "localhost"
    }
    return host, port, nil
}
```
Given that we bind the API server on all interfaces via `0.0.0.0`, the function returns `localhost`.

**Comment by alexbrand** [comment]
Another thing to notice in the error log is that `localhost` is being resolved to `10.189.173.96` for some reason. We have seen issues in the past where Go's DNS resolver gets tripped up under certain DNS configurations. Specifically, we saw an issue where a catch-all DNS entry would cause issues.

**Comment by TimWoolford** [comment]
DNS resolution for `localhost` was sent to our internal DNS server, which defaults its search to an internal domain.

Unfortunately a server named `localhost.<internal domain>.com` had registered a DNS record via DHCP. 

API server health checks were routed to this rogue server and failed, causing the API server to be restarted constantly.

We're looking at technical (and social 😈) methods from preventing this from happening again.

Is there a way to force the DNS lookup to use an `/etc/hosts` file before DNS?

Could the API server default to `127.0.0.1` instead of `localhost`?

Not exactly a KET issue, but is there a way we could use KET to configure this problem away?

**Comment by alexbrand** [comment]
@TimWoolford I believe you might be able to enforce DNS lookup order in your nsswitch.conf file. More info here: http://man7.org/linux/man-pages/man5/nsswitch.conf.5.html

This is somewhat outside of KET's reach, as it's an underlying infrastructure issue, and Kubernetes itself is what defaults to `localhost` instead of `127.0.0.1`. The one thing we can do is stop setting the `bind-address` to `0.0.0.0` (which would result in Kubernetes using whatever the advertise address is instead of `localhost`), but that needs more consideration on our side.

**Comment by TimWoolford** [comment]
Thanks for your help @alexbrand.

**Comment by alexbrand** [comment]
No problem @TimWoolford ! Glad we found the underlying issue.

**Comment by TimWoolford** [comment]
Possible work around: 

By default the Go DNS resolution uses initialy the server from `/etc/resolv.conf` file, not `/etc/hosts`.

Go can be forced to use the c libraries initially. Ref : [go net package docs](https://golang.org/pkg/net)

The easiest option seems to be to add a `LOCALDOMAIN` environment variable to the apiserver container.

```
    env:
      - name: LOCALDOMAIN
        value: ""
```

This can be done explicitly using `GODEBUG=netdns=cgo`, but I feel reluctant to use `GODEBUG`. 

What are your thoughts @alexbrand, @swade1987 ?

**Comment by TimWoolford** [comment]
Gradually filling gaps in my understanding...

The internal domain is getting added from the search list in the local `/etc/resolve.conf`. If I remove the problem internal domain from the resolv file, the apiserver does standup.

Now if we did this for all nodes, then we would need to use FQDNs for all hosts, which I was doing in KET-1.2.2, and a fix https://github.com/apprenda/kismatic/pull/484 has been merged to allow this in 1.3.1+.

@alexbrand - you mentioned some calico changes that may have to be made for this, or did I misunderstand?

**Comment by alexbrand** [comment]
We reached out to the calico team and they mentioned that it should be OK to rely on hostname auto-detection now that the calico-node process is deployed as a pod on the cluster.

**Comment by altaha** [comment]
@TimWoolford Wow I can't believe I ran into the exact same issue.. localhost.<internal domain>.com 🤦‍♂️ 

I used the LOCALDOMAIN env variable workaround as well. Thanks!

**Comment by TimWoolford** [comment]
Hi @altaha, our current solution is to remove all search domains from the resolv.conf file on each of the cluster VMs. This seems easier to control than ensuring that all k8s services that may use the go resolver have the env variable set. It also means we don't have to meddle with the KET config.

**Comment by wymarsalis** [comment]
Hi, using kismatic 1.5.3 and got the same error as @TimWoolford: 
`The connection to the server 127.0.0.1:6443 was refused`
even if I remove all search domains from the resolv.conf
I'll give a try to the second workaround, could you please tell me where should I set the variable LOCALDOMAIN ?
