### ISSUE TITLE
Unable to start calico-policy-controller pods after upgrading from v1.3.2 to v1.3.3

### ISSUE THREAD

**Issue by hreidar** [apprenda/kismatic#569]
Hi, I'm getting an error after upgrading from kismatic1.3.2 to kismatic1.3.3. I'm running a three node dev cluster on Ubuntu 16.04. I have already upgraded once before on the same cluster, from 1.2.2 to 1.3.2 without any problems.

The error:
```
2017-06-02T15:52:17.317154788Z 2017-06-02 15:52:17,316 7 INFO Configuring /etc/hosts
2017-06-02T15:52:17.318115415Z 2017-06-02 15:52:17,317 7 INFO Appended 'kubernetes.default  -> 172.17.0.1' to /etc/hosts
2017-06-02T15:52:17.318142521Z 2017-06-02 15:52:17,317 7 INFO Beginning execution
2017-06-02T15:52:17.319288644Z 2017-06-02 15:52:17,318 7 INFO Leader election enabled? False
2017-06-02T15:52:17.348649154Z Traceback (most recent call last):
2017-06-02T15:52:17.348721247Z   File "<string>", line 562, in <module>
2017-06-02T15:52:17.349044126Z   File "<string>", line 159, in run
2017-06-02T15:52:17.349078054Z   File "site-packages/pycalico/datastore.py", line 901, in delete_policy_tier
2017-06-02T15:52:17.349098896Z   File "site-packages/etcd/client.py", line 610, in delete
2017-06-02T15:52:17.349115926Z   File "site-packages/etcd/client.py", line 820, in wrapper
2017-06-02T15:52:17.349131653Z   File "site-packages/etcd/client.py", line 890, in api_execute
2017-06-02T15:52:17.34914836Z   File "site-packages/urllib3/request.py", line 66, in request
2017-06-02T15:52:17.349775254Z   File "site-packages/urllib3/request.py", line 87, in request_encode_url
2017-06-02T15:52:17.349850291Z   File "site-packages/urllib3/poolmanager.py", line 244, in urlopen
2017-06-02T15:52:17.349861178Z   File "site-packages/urllib3/connectionpool.py", line 600, in urlopen
2017-06-02T15:52:17.349868216Z   File "site-packages/urllib3/connectionpool.py", line 345, in _make_request
2017-06-02T15:52:17.349874438Z   File "site-packages/urllib3/connectionpool.py", line 844, in _validate_conn
2017-06-02T15:52:17.349880838Z   File "site-packages/urllib3/connection.py", line 333, in connect
2017-06-02T15:52:17.349888876Z   File "site-packages/urllib3/contrib/pyopenssl.py", line 343, in getpeercert
2017-06-02T15:52:17.349913715Z   File "site-packages/urllib3/contrib/pyopenssl.py", line 219, in get_subj_alt_name
2017-06-02T15:52:17.349922442Z   File "site-packages/urllib3/contrib/pyopenssl.py", line 175, in _dnsname_to_stdlib
2017-06-02T15:52:17.349930818Z   File "site-packages/urllib3/contrib/pyopenssl.py", line 173, in idna_encode
2017-06-02T15:52:17.349943122Z   File "site-packages/idna/core.py", line 350, in encode
2017-06-02T15:52:17.349951503Z idna.core.IDNAError: Empty domain
2017-06-02T15:52:17.349959245Z controller returned -1
```
and here is the k8s specs after the upgrade:
```
root@kube-dev-master1:/etc/kubernetes/specs# cat policy-controller.yaml 
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: calico-policy-controller
  namespace: kube-system
  labels:
    tier: control-plane
    k8s-app: calico-policy-controller
  annotations:
    kismatic/version: "1.3.3"
spec:
  # The policy controller can only have a single active instance.
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      name: calico-policy-controller
      namespace: kube-system
      labels:
        tier: control-plane
        k8s-app: calico-policy-controller
    spec:
      # The policy controller must run in the host network namespace so that
      # it isn't governed by policy that would prevent it from working.
      hostNetwork: true
      volumes:
        - name: "ca"
          hostPath:
            path: "/etc/kubernetes/ca.pem"
        - name: "cert"
          hostPath:
            path: "/etc/kubernetes/kubenode.pem"
        - name: "key"
          hostPath:
            path: "/etc/kubernetes/kubenode-key.pem"
      containers:
        - name: calico-policy-controller
          image: calico/kube-policy-controller:v0.6.0
          volumeMounts:
            - mountPath: "/etc/kubernetes/ca.pem"
              name: "ca"
            - mountPath: "/etc/kubernetes/kubenode.pem"
              name: "cert"
            - mountPath: "/etc/kubernetes/kubenode-key.pem"
              name: "key"
          env:
            # The location of the Calico etcd cluster.
            - name: ETCD_ENDPOINTS
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_endpoints
            # Location of the CA certificate for etcd.
            - name: ETCD_CA_CERT_FILE
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_ca
            # Location of the client certificate for etcd.
            - name: ETCD_CERT_FILE
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_cert
            # Location of the client key for etcd.
            - name: ETCD_KEY_FILE
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_key
            # The location of the Kubernetes API.  Use the default Kubernetes
            # service for API access.
            - name: K8S_API
              value: "https://#.#.#.#:6443"
            - name: CONFIGURE_ETC_HOSTS
              value: "true"
root@kube-dev-master1:/etc/kubernetes/specs# 
```
Any idea what could be wrong?

**Comment by dkoshkin** [comment]
Hi @hreidar what are you using as your `FQDN` address?

**Comment by hreidar** [comment]
Hi @dkoshkin, here is my kismatic-cluster file with pass and IP omitted:

```
cluster:
  name: kube-dev-cluster1
  admin_password: ################    
  allow_package_installation: true     
  disconnected_installation: false     
  networking:
    type: routed                       
    pod_cidr_block: 172.16.0.0/16      
    service_cidr_block: 172.17.0.0/16  
    policy_enabled: false              
    update_hosts_files: true           
  certificates:
    expiry: 43800h                     
  ssh:
    user: kismaticuser
    ssh_key: /opt/kismatic.1.2.2/kismaticuser.key           
    ssh_port: 22
docker_registry:                       
  setup_internal: true                 
  address: ""                          
  port: 8443                           
  CA: ""                               
etcd:                                  
  expected_count: 1
  nodes:
  - host: "kube-dev-etcd1"             
    ip: "#.#.#.#"                
    internalip: ""                     
master:                                
  expected_count: 1
  load_balanced_fqdn: "#.#.#.#"                 
  load_balanced_short_name: "#.#.#.#"           
  nodes:
  - host: "kube-dev-master1"
    ip: "#.#.#.#"
    internalip: ""
worker:                                  
  expected_count: 1
  nodes:
  - host: "kube-dev-worker1"
    ip: "#.#.#.#"
    internalip: ""
ingress:
  expected_count: 0
  nodes: []
storage:
  expected_count: 0
  nodes: []
nfs:                                     
  nfs_volume: []
```

**Comment by hreidar** [comment]
@dkoshkin I'm not using any domain in this dev setup. Is that mandatory? if so can I update using kismatic?

**Comment by dkoshkin** [comment]
@hreidar no it should not be required.
What does your `/etc/cni/net.d/10-calico.conf` look like?(comment out any secrets)

**Comment by hreidar** [comment]
Here it is, they are identical on the master and worker:
```
hreidar@kube-dev-master1:~$ cat /etc/cni/net.d/10-calico.conf
{
    "name": "k8s-pod-network",
    "type": "calico",
    "etcd_endpoints": "https://kube-dev-etcd1:6666",
    "etcd_cert_file": "/etc/kubernetes/kubenode.pem",
    "etcd_key_file": "/etc/kubernetes/kubenode-key.pem",
    "etcd_ca_cert_file": "/etc/kubernetes/ca.pem",
    "log_level": "info",
    "ipam": {
        "type": "calico-ipam"
    },
    "policy": {
      "type": "k8s"
    },
    "kubernetes": {
        "kubeconfig": "/var/lib/kubelet/kubeconfig"
    }
}
hreidar@kube-dev-master1:~$
hreidar@kube-dev-master1:~$ cat /etc/hosts
127.0.0.1       localhost

# The following lines are desirable for IPv6 capable hosts
::1     localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
# Kismatic hosts BEGIN
#.#.#.# kube-dev-worker1
#.#.#.# kube-dev-master1
#.#.#.# kube-dev-etcd1
# Kismatic hosts END
hreidar@kube-dev-master1:~$ 
```

**Comment by hreidar** [comment]
@dkoshkin, I'm still experiencing the same problem. I did setup another dev cluster which has 3 etcd nodes, 2 master nodes and 2 worker nodes like my production cluster. I started installing version 1.2.2, then migrated to version 1.3.2 without any issues. Next I upgraded to version 1.4.0 but got stuck on task "wait until policy controller pods are ready" with the same error from the policy controller pod: " idna.core.IDNAError: Empty domain". I then tried to upgrade to version 1.4.1 with the same resaults.

Any ideas how I can resolve this issue?

**Comment by hreidar** [comment]
Little more info from my cluster:

```
root@kube-kismatic:/opt/dev-kismatic.1.4.1# kubectl get pods -n kube-system --kubeconfig generated/kubeconfig
NAME                                        READY     STATUS             RESTARTS   AGE
calico-node-17217                           2/2       Running            0          23h
calico-node-2pc98                           2/2       Running            0          23h
calico-node-j286z                           2/2       Running            0          23h
calico-node-m4wmw                           2/2       Running            0          23h
calico-policy-controller-4263576054-9v7nz   0/1       CrashLoopBackOff   282        23h
kube-apiserver-kube-dev-master1             1/1       Running            0          23h
kube-apiserver-kube-dev-master2             1/1       Running            0          23h
kube-controller-manager-kube-dev-master1    1/1       Running            0          23h
kube-controller-manager-kube-dev-master2    1/1       Running            0          23h
kube-dns-1564199188-hrtzw                   1/3       CrashLoopBackOff   593        23h
kube-dns-1564199188-vtwpt                   1/3       CrashLoopBackOff   593        23h
kube-proxy-kube-dev-master1                 1/1       Running            0          23h
kube-proxy-kube-dev-master2                 1/1       Running            0          23h
kube-proxy-kube-dev-worker1                 1/1       Running            0          23h
kube-proxy-kube-dev-worker2                 1/1       Running            0          23h
kube-scheduler-kube-dev-master1             1/1       Running            2          23h
kube-scheduler-kube-dev-master2             1/1       Running            0          23h
kubernetes-dashboard-2917854236-fjxwg       0/1       CrashLoopBackOff   302        23h
kubernetes-dashboard-2917854236-s962d       0/1       CrashLoopBackOff   331        23h
root@kube-kismatic:/opt/dev-kismatic.1.4.1# 
root@kube-kismatic:/opt/dev-kismatic.1.4.1# kubectl logs -f calico-policy-controller-4263576054-9v7nz -n kube-system --kubeconfig generated/kubeconfig         
Traceback (most recent call last):
  File "<string>", line 27, in <module>
  File "/usr/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "handlers/network_policy.py", line 26, in <module>
  File "site-packages/pycalico/datastore.py", line 251, in __init__
  File "site-packages/etcd/client.py", line 202, in __init__
  File "site-packages/etcd/client.py", line 283, in machines
  File "site-packages/urllib3/request.py", line 66, in request
  File "site-packages/urllib3/request.py", line 87, in request_encode_url
  File "site-packages/urllib3/poolmanager.py", line 244, in urlopen
  File "site-packages/urllib3/connectionpool.py", line 600, in urlopen
  File "site-packages/urllib3/connectionpool.py", line 345, in _make_request
  File "site-packages/urllib3/connectionpool.py", line 844, in _validate_conn
  File "site-packages/urllib3/connection.py", line 333, in connect
  File "site-packages/urllib3/contrib/pyopenssl.py", line 343, in getpeercert
  File "site-packages/urllib3/contrib/pyopenssl.py", line 219, in get_subj_alt_name
  File "site-packages/urllib3/contrib/pyopenssl.py", line 175, in _dnsname_to_stdlib
  File "site-packages/urllib3/contrib/pyopenssl.py", line 173, in idna_encode
  File "site-packages/idna/core.py", line 350, in encode
idna.core.IDNAError: Empty domain
controller returned -1
root@kube-kismatic:/opt/dev-kismatic.1.4.1#
root@kube-kismatic:/opt/dev-kismatic.1.4.1# kubectl describe pods calico-policy-controller-4263576054-9v7nz -n kube-system --kubeconfig generated/kubeconfig
Name:           calico-policy-controller-4263576054-9v7nz
Namespace:      kube-system
Node:           kube-dev-worker1/#.#.#.#
Start Time:     Mon, 21 Aug 2017 16:45:58 +0000
Labels:         k8s-app=calico-policy-controller
                pod-template-hash=4263576054
                tier=control-plane
Annotations:    kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"kube-system","name":"calico-policy-controller-4263576054","uid":"c73f9538-8684-11...
Status:         Running
IP:             #.#.#.#
Controllers:    ReplicaSet/calico-policy-controller-4263576054
Containers:
  calico-policy-controller:
    Container ID:       docker://897e7fdb7568743176928cd64da87a3da0a48fd32d0f0a668fd36affb1e9975b
    Image:              calico/kube-policy-controller:v0.6.0
    Image ID:           docker-pullable://calico/kube-policy-controller@sha256:54b4872a6fff0c8278266d05108da190f374b9500079769306047fc3da30d771
    Port:
    State:              Waiting
      Reason:           CrashLoopBackOff
    Last State:         Terminated
      Reason:           Error
      Exit Code:        255
      Started:          Wed, 23 Aug 2017 08:39:05 +0000
      Finished:         Wed, 23 Aug 2017 08:39:06 +0000
    Ready:              False
    Restart Count:      471
    Environment:
      ETCD_ENDPOINTS:           <set to the key 'etcd_endpoints' of config map 'calico-config'> Optional: false
      ETCD_CA_CERT_FILE:        <set to the key 'etcd_ca' of config map 'calico-config'>        Optional: false
      ETCD_CERT_FILE:           <set to the key 'etcd_cert' of config map 'calico-config'>      Optional: false
      ETCD_KEY_FILE:            <set to the key 'etcd_key' of config map 'calico-config'>       Optional: false
      K8S_API:                  https://#.#.#.#:6443
      CONFIGURE_ETC_HOSTS:      true
    Mounts:
      /etc/kubernetes/pki/ca.pem from ca (rw)
      /etc/kubernetes/pki/etcd-client-key.pem from key (rw)
      /etc/kubernetes/pki/etcd-client.pem from cert (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-n60kl (ro)
Conditions:
  Type          Status
  Initialized   True 
  Ready         False 
  PodScheduled  True 
Volumes:
  ca:
    Type:       HostPath (bare host directory volume)
    Path:       /etc/kubernetes/pki/ca.pem
  cert:
    Type:       HostPath (bare host directory volume)
    Path:       /etc/kubernetes/pki/etcd-client.pem
  key:
    Type:       HostPath (bare host directory volume)
    Path:       /etc/kubernetes/pki/etcd-client-key.pem
  default-token-n60kl:
    Type:       Secret (a volume populated by a Secret)
    SecretName: default-token-n60kl
    Optional:   false
QoS Class:      BestEffort
Node-Selectors: <none>
Tolerations:    <none>
Events:
  FirstSeen     LastSeen        Count   From                            SubObjectPath                                   Type            Reason          Message
  ---------     --------        -----   ----                            -------------                                   --------        ------          -------
  1d            4m              472     kubelet, kube-dev-worker1       spec.containers{calico-policy-controller}       Normal          Pulled          Container image "calico/kube-policy-controller:v0.6.0" already present on machine
  1d            4m              472     kubelet, kube-dev-worker1       spec.containers{calico-policy-controller}       Normal          Created         Created container
  1d            4m              472     kubelet, kube-dev-worker1       spec.containers{calico-policy-controller}       Normal          Started         Started container
  1d            12s             10738   kubelet, kube-dev-worker1       spec.containers{calico-policy-controller}       Warning         BackOff         Back-off restarting failed container
  1d            12s             10738   kubelet, kube-dev-worker1                                                       Warning         FailedSync      Error syncing pod
root@kube-kismatic:/opt/dev-kismatic.1.4.1# 
```

**Comment by dkoshkin** [comment]
@hreidar have you tried upgrading from `v1.3.3` to `v1.4.1` directly.

This is due to a few factors but mainly new certs are not being picked up by etcd. This was fixed in `v1.4.1` in https://github.com/apprenda/kismatic/pull/631.

**Comment by hreidar** [comment]
@dkoshkin no I did go from 1.3.2 straight to 1.4.0 and then to 1.4.1. I was hoping to skip this issue which I thought was bound to version 1.3.3 but fixed there after.

Is there any manual way to update them?

**Comment by hreidar** [comment]
Another thing, looking at the certs on one of my etcd node it seems to be the upgraded one:

```
root@kube-dev-etcd1:/etc/etcd_k8s# openssl x509 -text -noout -in /etc/etcd_networking/etcd.pem
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            10:4f:00:c2:a8:03:f6:57:8e:a7:0c:7f:a3:b9:3e:e2:7f:69:9b:c7
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: C=US, ST=NY, L=Troy, O=Apprenda, OU=Kismatic, CN=kube-dev-cluster1
        Validity
            Not Before: Aug 21 14:48:00 2017 GMT
            Not After : Aug 21 14:48:00 2018 GMT
        Subject: CN=kube-dev-etcd1
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    00:b5:54:cf:82:e6:0f:a9:2a:22:78:f3:66:8e:f6:
                    a3:44:16:93:27:6b:0f:85:5c:67:03:c8:1f:4c:ae:
                    28:94:b6:62:e6:32:00:ce:ef:16:28:b4:14:23:0f:
                    31:d0:cf:52:85:12:40:a0:6f:7e:57:17:05:0f:28:
                    aa:11:88:c0:4b:20:08:72:8e:fb:cd:f4:96:b4:fe:
                    59:f0:ec:b0:25:cb:87:6c:59:0d:78:90:3e:61:16:
                    d1:f9:69:34:af:31:37:9c:af:ee:79:37:f7:b4:b1:
                    c7:dc:c5:30:0b:54:22:ce:9b:95:e3:36:f1:23:d2:
                    72:07:db:92:31:e7:58:6f:da:d9:13:72:8e:9e:30:
                    d8:55:7a:fa:a3:38:10:ba:c2:44:d1:18:35:f2:23:
                    7e:86:52:a3:77:37:5f:a5:3b:af:32:6e:fc:65:4b:
                    79:2f:e5:16:79:2f:b6:33:2c:e7:3d:bd:1e:48:ab:
                    6e:bc:dc:24:ba:b8:87:cf:97:9e:13:4b:54:92:de:
                    0d:ff:6c:93:bb:8b:1e:53:27:bc:0f:a0:5e:55:ca:
                    06:19:fb:bf:f2:a2:1b:21:d0:24:89:88:c2:7c:27:
                    ea:8d:49:c9:a0:54:ea:4a:5a:52:23:14:cc:0e:28:
                    06:38:e1:8c:29:a6:2e:35:86:92:97:e1:22:41:ac:
                    0b:73
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment
            X509v3 Extended Key Usage: 
                TLS Web Server Authentication, TLS Web Client Authentication
            X509v3 Basic Constraints: critical
                CA:FALSE
            X509v3 Subject Key Identifier: 
                DF:C7:89:BE:8B:73:D5:D6:6F:63:11:0F:B0:D2:9C:36:B2:1C:CA:EC
            X509v3 Authority Key Identifier: 
                keyid:A9:FB:76:AB:84:82:BC:05:E3:AB:75:1B:6C:7B:6F:94:4F:83:87:93

            X509v3 Subject Alternative Name: 
                DNS:kube-dev-etcd1, IP Address:#.#.#.#, IP Address:127.0.0.1
    Signature Algorithm: sha256WithRSAEncryption
         69:9a:0a:0f:f2:e3:a7:af:05:74:12:c4:da:4b:dc:9f:41:c8:
         c6:4e:34:f0:3b:25:b6:26:bb:bf:62:f6:97:6d:39:e0:97:74:
         e0:37:d0:5d:82:4e:4d:72:39:ca:84:db:c1:7a:3b:a0:66:a4:
         c9:94:c9:31:7c:8c:98:89:13:3c:62:0e:2a:0a:93:54:21:b1:
         32:57:29:f4:8e:46:be:60:9f:c6:c7:60:67:6e:fd:9e:0a:3c:
         d1:8c:cb:11:89:de:b4:d6:c6:08:44:4f:34:5e:07:01:62:f9:
         06:00:7a:a2:5e:07:ec:ec:5f:40:d3:2e:d4:f1:b3:4e:eb:f9:
         b4:52:a2:d9:1a:24:c1:c6:7b:a8:c7:91:ac:4c:73:8e:da:47:
         78:d3:07:fe:a8:8a:a5:1d:4c:0b:86:1f:3f:f3:78:a1:ef:42:
         59:49:c1:9a:3f:44:d8:d6:18:a8:51:fc:97:36:98:49:03:af:
         37:62:14:5a:db:c6:d9:46:fd:7c:a7:5b:a8:87:59:ca:88:68:
         ec:8b:08:4a:9f:a6:87:42:d0:3b:cf:d6:8d:93:8e:de:99:01:
         8c:99:cd:79:ef:da:2a:9b:15:83:b5:23:db:5f:5c:83:0b:fb:
         17:c7:8e:fb:07:68:63:d8:08:7f:30:22:cb:b6:00:7b:67:40:
         b6:6b:fb:37
root@kube-dev-etcd1:/etc/etcd_k8s#
```

**Comment by dkoshkin** [comment]
How long has the etcd service been running, `sysyemctl status etcd_networking`

**Comment by hreidar** [comment]
Since two days ago
```
root@kube-dev-etcd1:/etc/etcd_k8s# systemctl status etcd_networking    
● etcd_networking.service - etcd key-value store
   Loaded: loaded (/etc/systemd/system/etcd_networking.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2017-08-21 14:57:55 GMT; 2 days ago
     Docs: https://github.com/coreos/etcd
 Main PID: 21346 (etcd_networking)
    Tasks: 8
   Memory: 29.6M
      CPU: 54min 56.280s
   CGroup: /system.slice/etcd_networking.service
           └─21346 /usr/bin/etcd_networking --name=kube-dev-etcd1 --data-dir=/var/lib/etcd_networking --client-cert-auth --cert-file=/etc/etcd_networking/etcd.pem --key-file=/etc/etcd_network

```

**Comment by hreidar** [comment]
@dkoshkin after restarting the etcd_networking service I have successfully run the Kismatic upgrade process. Thanks for your time on this. Maybe it would be worth the while adding this "restart" step into the upgrade role.
