### ISSUE TITLE
Reinstall with existing certs fails.

### ISSUE THREAD

**Issue by jarkomes** [apprenda/kismatic#604]
Case:
We have reinstalled our kismatic k8s cluster and while reinstalling we went from 3 to 6 machines.
We wanted to keep the certificated from the previous installation (3 machines) since we have them configured in jenkins etc...

Issue:
After reinstalling, the  calico policy controller goes in a crashloop:
```
Traceback (most recent call last):
  File "<string>", line 27, in <module>
  File "/usr/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "handlers/network_policy.py", line 26, in <module>
  File "site-packages/pycalico/datastore.py", line 251, in __init__
  File "site-packages/etcd/client.py", line 202, in __init__
  File "site-packages/etcd/client.py", line 283, in machines
  File "site-packages/urllib3/request.py", line 66, in request
  File "site-packages/urllib3/request.py", line 87, in request_encode_url
  File "site-packages/urllib3/poolmanager.py", line 244, in urlopen
  File "site-packages/urllib3/connectionpool.py", line 600, in urlopen
  File "site-packages/urllib3/connectionpool.py", line 345, in _make_request
  File "site-packages/urllib3/connectionpool.py", line 844, in _validate_conn
  File "site-packages/urllib3/connection.py", line 333, in connect
  File "site-packages/urllib3/contrib/pyopenssl.py", line 343, in getpeercert
  File "site-packages/urllib3/contrib/pyopenssl.py", line 219, in get_subj_alt_name
  File "site-packages/urllib3/contrib/pyopenssl.py", line 175, in _dnsname_to_stdlib
  File "site-packages/urllib3/contrib/pyopenssl.py", line 173, in idna_encode
  File "site-packages/idna/core.py", line 350, in encode
idna.core.IDNAError: Empty domain
controller returned -1
```
Solution for us:
Reinstalled the cluster again, but let the certificates be regenerated. This made the Calico Policy Controller work again and we can use our cluster again.

**Comment by dkoshkin** [comment]
@jarkomes Did you delete all certs including the CA?

**Comment by dkoshkin** [comment]
What version of KET are you using for the install, also was the original cluster installed with the same version of KET?

**Comment by jarkomes** [comment]
Original version was 1.3.2, we reinstalled with 1.3.3
we deleted all certs to make it work, did not test with only deleting node certs.
